[package]
name = "lib-adapter"
version = "0.1.0"
description = "An adapter lib"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lib_adapter"

[features]

[dependencies]
anchor-lang = "0.26.0"
