[features]
seeds = false
skip-lint = false
[programs.localnet]
vaults = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chase/.config/solana/id.json"

[scripts]
test = "yarn workspace anchor-tests run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
