[workspace]
members = [
    "lib-adapter",
    "programs/*",
    "external/marinade/libs/marinade-anchor-sdk",
    "external/cpi-interface"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
