[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[config]
init_task = "init"
skip_core_tasks = true

[tasks.init]
script ='''
cargo build --package lib-adapter || exit 1
echo TEST4
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
LIB="./lib-adapter/src/_shared"

for DESTINATION in ./programs/*/src; do
  cp -fru "$LIB" "$DESTINATION"
done
'''

[tasks.test]
workspace = false
command = "anchor"
args = ["test"]

[tasks.build]
workspace = false
command = "anchor"
args = ["build"]